apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-d
  namespace: expense
  labels: # these labels are replicaset labels
    project: expense
    module: frontend
    tier: web
spec:
  # modify replicas according to your case
  replicas: 1
  selector:
    matchLabels:
    # these are used to select the pod to create replicas
      tier: web
      project: expense
      module: frontend
    # this is pod defination
  template:
    metadata:
      namespace: expense
    # these labels belong to pod
      labels:
        tier: web
        project: expense
        module: frontend
    spec:
      containers:
        - name: frontend
          image: hemanthkumar75/frontend:v1
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: expense
spec:
  type: LoadBalancer
  selector:
    app: web
    tier: frontend
    project: expense
  ports:
  - name: nginx-svc-port
    protocol: TCP
    port: 80
    targetPort: 80