apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: expense
spec:
  selector:
    app: web
    tier: frontend
    project: expense
  ports:
  - name: nginx-svc-port
    protocol: TCP
    port: 80
    targetPort: 80