apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment-set
  namespace: expense
  labels: # these labels are replicaset labels
    app: web
    tier: frontend
    project: expense
spec:
  # modify replicas according to your case
  replicas: 2
  type: LoadBalancer
  selector:
    matchLabels:
    # these are used to select the pod to create replicas
      app: web
      tier: frontend
      project: expense
    # this is pod defination
  template:
    metadata:
      namespace: expense
    # these labels belong to pod
      labels:
        app: web
        tier: frontend
        project: expense
    spec:
      containers:
      - name: nginx
        image: nginx:stable-perl
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: expense
spec:
  selector:
    app: web
    tier: frontend
    project: expense
  ports:
  - name: nginx-svc-port
    protocol: TCP
    port: 80
    targetPort: 80
