apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: expense
  labels:
    project: expense
    tier: api
    module: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      project: expense
      tier: api
      module: backend
  template:
    metadata:
      labels:
        project: expense
        tier: api
        module: backend
    spec:
      containers:
        - name: backend
          image: ashwani525/backend:v1
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: expense
spec:
  type: ClusterIP
  selector:
    tier: api
    project: expense
    module: backened
  ports:
    - name: nginx-svc-port
      protocol: TCP
      port: 8080
      targetPort: 8080