apiVersion: v1
kind: ConfigMap
metadata:
  name: backend
  namespace: expense
  labels:
    app: backend-mysql
data:
  DB_HOST: mysql
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: expense
  labels:
    project: expense
    environment: dev
    created_by: HemanthKumar
    module: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      project: expense
      environment: dev
      created_by: HemanthKumar
      module: backend
  template:
    metadata:
      labels:
        project: expense
        environment: dev
        created_by: HemanthKumar
        module: backend
    spec:
      containers:
        - name: backend
          image: hemanthkumar75/backend:v1
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: backend
          ports:
            - containerPort: 8080
---
kind: Service
apiVersion: v1
metadata:
  name: backend
  namespace: expense
spec:
  selector:
    project: expense
    environment: dev
    created_by: HemanthKumar
    module: backend
  type: ClusterIP
  ports:
    - name: backend
      protocol: TCP
      port: 8080
      targetPort: 8080