apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-d
  namespace: expense
  labels: # these labels are replicaset labels
    project: expense
    module: backend
    tier: api
spec:
  # modify replicas according to your case
  replicas: 2
  selector:
    matchLabels:
    # these are used to select the pod to create replicas
      tier: api
      project: expense
      module: backend
    # this is pod defination
  template:
    metadata:
      namespace: expense
    # these labels belong to pod
      labels:
        tier: api
        project: expense
        module: backend
    spec:
      containers:
        - name: backend
          image: nginx:stable-perl
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: expense
spec:
  type: ClusterIP
  selector:
    tier: api
    project: expense
    module: backened
  ports:
    - name: nginx-svc-port
      protocol: TCP
      port: 8080
      targetPort: 8080