apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: expense
spec:
  type: ClusterIP
  selector:
    tier: api
    project: expense
    module: backened
  ports:
    - name: nginx-svc-port
      protocol: TCP
      port: 8080
      targetPort: 8080