apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment-set
  namespace: expense
  labels: # these labels are replicaset labels
    app: db
    tier: mysql
    project: expense
spec:
  # modify replicas according to your case
  replicas: 1
  selector:
    matchLabels:
    # these are used to select the pod to create replicas
      app: db
      tier: mysql
      project: expense
    # this is pod defination
  template:
    metadata:
      namespace: expense
    # these labels belong to pod
      labels:
        app: db
        tier: mysql
        project: expense
    spec:
      containers:
      - name: nginx
        image: nginx:stable-perl
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: expense
spec:
  selector:
    app: db
    tier: mysql
    project: expense
  ports:
  - name: nginx-svc-port
    protocol: TCP
    port: 3306
    targetPort: 3306
